version: "3"
services:
  simple-ecommerce-prj:
    image: simple-ecommerce-prj
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      DB_HOST: postgresdb
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DB_PORT: 5432
  postgresdb: 
    container_name: postgresdb
    image: postgres
    volumes:
      - [SOME_PATH]/db:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    environment:
      POSTGRES_DB: simple-ecommerce-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
